---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.name" . }}
  labels:
    {{ include "common.labelsApp" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      {{ include "common.selectorLabelsApp" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "common.labelsApp" . | nindent 8 }}
        orleans/serviceId: {{ tpl .Values.environment.orleans.serviceId . }}
        orleans/clusterId: {{ tpl .Values.environment.orleans.clusterId . }}
    spec:
      serviceAccountName: {{ include "common.name" . }}
      containers:
        - name: cloud-sql-proxy
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.2"
          image: {{ .Values.cloudSQL.image }}
          command: [ "/cloud-sql-proxy" ]
          args:
            - "--private-ip"
            - "--structured-logs"
            - "--port=5432"
            - "{{ .Values.cloudSQL.connectionName }}"
          securityContext:
            runAsNonRoot: true
        - image: google/cloud-sdk:slim
          name: workload-identity-test
          command: [ "sleep","infinity" ]
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.url }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
{{/*          command: [ "sleep","infinity" ]*/}}
          readinessProbe:
            httpGet:
              path: /health
              port: signalr
            periodSeconds: 2
            timeoutSeconds: 1
            successThreshold: 2
            failureThreshold: 2
          ports:
            - name: signalr
              containerPort: {{ .Values.environment.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: LOGGING_ENVIRONMENT
              value: "container"
            - name: ORLEANS_SERVICE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['orleans/serviceId']
            - name: ORLEANS_CLUSTER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['orleans/clusterId']
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DOTNET_SHUTDOWNTIMEOUTSECONDS
              value: "120" # Orleans Silo requires time to shut down all the grains and remove itself the membership table
{{/*    volumeMounts:*/}}
{{/*      - name: configuration*/}}
{{/*        mountPath: "/app/WordleArena/appsettings.json"*/}}
{{/*        subPath: appsettings.json*/}}
{{/*    volumes:*/}}
{{/*      - name: configuration*/}}
{{/*        configMap:*/}}
{{/*          name: {{ include "common.name" . }}-configuration*/}}
{{/*      terminationGracePeriodSeconds: 180*/}}