---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.name" . }}
  labels:
    {{ include "common.labelsApp" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gcpServiceAccount }}
